# Generated by Django 5.0 on 2023-12-20 06:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp1", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="restaurant",
            name="completed",
        ),
        migrations.AddField(
            model_name="restaurant",
            name="address",
            field=models.CharField(default="", max_length=280),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="cuisine",
            field=models.CharField(default="", max_length=40),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="description",
            field=models.CharField(default="", max_length=280),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="images",
            field=models.ImageField(blank=True, null=True, upload_to="uploadedimages/"),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="title",
            field=models.CharField(default="", max_length=200),
        ),
    ]
